Задачи раздела №2
js-tasks-ru/js-20200928_ser-lapteff pull request #2
Opened 2020-10-05 14:49 UTC by serlapteff

Реализация функций sortStrings, pick, omit

2020-10-05 14:58 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

```diff
sortStrings
+ should return sorted by "asc" array of strings
+ should return a new sorted array
+ should return sorted by "desc" array of strings in "en" locale
+ should correctly sort language-specific characters in "ru" locale
+ should correctly sort strings started from uppercase
- should correctly sort strings for mixed "en" and "ru" locales
```
```diff
pick
+ should return new object with one passed field
+ should return new object with a few passed field
+ should return an empty object if passed fields does not found
```
```diff
omit
+ should return a new object without passed field
+ should return a new object without few passed fields
+ should return initial object if passed fields doesn't found
```

2020-10-05 15:08 UTC, jsru commented
Поздравляю, все задачи решены абсолютно верно
```diff
sortStrings
+ should return sorted by "asc" array of strings
+ should return a new sorted array
+ should return sorted by "desc" array of strings in "en" locale
+ should correctly sort language-specific characters in "ru" locale
+ should correctly sort strings started from uppercase
+ should correctly sort strings for mixed "en" and "ru" locales
```
```diff
pick
+ should return new object with one passed field
+ should return new object with a few passed field
+ should return an empty object if passed fields does not found
```
```diff
omit
+ should return a new object without passed field
+ should return a new object without few passed fields
+ should return initial object if passed fields doesn't found
```

Добавляю преподавателя (@dosandk) для код-ревью, посмотрим что он скажет :)

2020-10-06 13:45 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> +  const copyArr = arr.slice();
стоит использовать `[...arr]` вместо `arr.slice`

2020-10-06 13:46 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> +      return copyArr.sort( (a, b) => {
строки 11-13 дублируют строки 16-18 за исключением порядка символов в `localCompare`
Попробуйте избавиться от дублирования кода

2020-10-06 13:47 UTC, dosandk commented on 02-javascript-data-types/3-omit/index.js
> +  for (let field of Object.entries(obj)) {
почему для решения `omit` Вы выбрали итерациб по объекту, а в решении `pick` по `fields`?

2020-10-06 13:47 UTC, dosandk requested changes
необходимо внести правки согласно комментариям,
дать ответы на вопросы

2020-10-06 17:50 UTC, serlapteff commented on 02-javascript-data-types/3-omit/index.js
> +  for (let field of Object.entries(obj)) {
В функции pick решил проитерировать строки и сравнить их с ключами объекта, а в omit сделать наоборот. Такое решение для pick неверное?

2020-10-06 18:03 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @dosandk

2020-10-07 18:33 UTC, dosandk commented on 02-javascript-data-types/3-omit/index.js
> +  for (let field of Object.entries(obj)) {
более предпочтителное решение - обход свойств объекта, тогда мы сможем избежать использования оператора `in` - подробнее поговорим на занятии.
оба решения принимаются

2020-10-07 18:33 UTC, dosandk approved these changes

2020-10-07 18:33 UTC, merged